# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ruff: noqa

"""Example RAG data ingestion component — customize for your data source.

Out of the box, generates a synthetic Q&A dataset inline in BigQuery
and chunks it for Vector Search 2.0, so the pipeline runs end-to-end
without external setup.

To use your own data, replace the CTE in `fetch_sample_data` with a
query against your source table and adjust the downstream processing
(HTML→markdown, chunking, dedup) to match its schema.

Helpful references:
- Query Cloud Storage data directly from BigQuery (no load step):
  https://docs.cloud.google.com/bigquery/docs/query-cloud-storage-data
- BigQuery Python UDFs to push markdown conversion and chunking into
  BigQuery for parallel execution on large datasets:
  https://docs.cloud.google.com/bigquery/docs/user-defined-functions-python
"""

from google_cloud_pipeline_components.types.artifact_types import BQTable
from kfp.dsl import Output, component


@component(
    base_image="python:3.11-slim",
    packages_to_install=[
        "backoff>=2.2.0",
        "bigframes>=2.0.0",
        "google-cloud-aiplatform>=1.80.0",
        "google-cloud-bigquery>=3.0.0",
        "google-cloud-pipeline-components>=2.19.0",
        "google-cloud-vectorsearch>=0.4.0",
        "kfp>=1.4.0",
        "langchain-text-splitters>=0.3.0",
        "markdownify>=0.14.0",
        "pandas<3",
        "swifter>=1.4.0",
    ],
)
def process_data(
    project_id: str,
    schedule_time: str,
    output_table: Output[BQTable],
    is_incremental: bool = True,
    look_back_days: int = 1,
    chunk_size: int = 1500,
    chunk_overlap: int = 20,
    max_rows: int = 100,
    destination_dataset: str = "qa_data",
    destination_table: str = "incremental_questions_embeddings",
    deduped_table: str = "questions_embeddings",
    location: str = "us-central1",
) -> None:
    """Process Q&A data by:
    1. Fetching data from BigQuery
    2. Converting HTML to markdown
    3. Splitting text into chunks
    4. Storing results in BigQuery

    Embeddings are auto-generated by Vector Search 2.0 during ingestion.

    Args:
        output_table: Output BQ table artifact
        is_incremental: Whether to process only recent data
        look_back_days: Number of days to look back for incremental processing
        chunk_size: Size of text chunks
        chunk_overlap: Overlap between chunks
        max_rows: Maximum number of questions to fetch (0 for unlimited)
        destination_dataset: BigQuery dataset for storing results
        destination_table: Table for storing incremental results
        deduped_table: Table for storing deduplicated results
        location: BigQuery location
    """
    import logging
    from datetime import datetime, timedelta, timezone

    import bigframes.pandas as bpd
    import swifter
    from google.cloud import bigquery
    from langchain_text_splitters import RecursiveCharacterTextSplitter
    from markdownify import markdownify

    # Initialize logging
    logging.basicConfig(level=logging.INFO)
    logging.info(f"Using {swifter} for apply operations.")

    # Initialize clients
    logging.info("Initializing clients...")
    bq_client = bigquery.Client(project=project_id, location=location)
    bpd.options.bigquery.project = project_id
    bpd.options.bigquery.location = location
    logging.info("Clients initialized.")

    # Set date range for data fetch
    schedule_time_dt: datetime = datetime.fromisoformat(
        schedule_time.replace("Z", "+00:00")
    )
    if schedule_time_dt.year == 1970:
        logging.warning(
            "Pipeline schedule not set. Setting schedule_time to current date."
        )
        schedule_time_dt = datetime.now(timezone.utc)

    START_DATE: datetime = schedule_time_dt - timedelta(
        days=look_back_days
    )  # Start date for data processing window
    END_DATE: datetime = schedule_time_dt  # End date for data processing window

    logging.info(f"Date range set: START_DATE={START_DATE}, END_DATE={END_DATE}")

    def fetch_sample_data(start_date: str, end_date: str) -> bpd.DataFrame:
        """Fetch synthetic Q&A from an inline BigQuery CTE — replace for real data."""
        limit_clause = f"LIMIT {max_rows}" if max_rows > 0 else ""
        query = f"""
            WITH questions AS (
                SELECT 1001 AS question_id,
                       "How do I reverse a list in Python?" AS question_title,
                       "<p>I have a list of integers and want to reverse it in place. What is the most idiomatic way?</p><pre><code>nums = [1, 2, 3, 4, 5]</code></pre>" AS question_body,
                       ["<p>Use the in-place <code>list.reverse()</code> method:</p><pre><code>nums.reverse()</code></pre>",
                        "<p>Or get a reversed copy with slicing:</p><pre><code>reversed_nums = nums[::-1]</code></pre>"] AS answers
                UNION ALL SELECT 1002, "What is the difference between a list and a tuple?",
                    "<p>Both look similar but I am not sure when to use one over the other. When should I prefer a tuple?</p>",
                    ["<p>Lists are mutable and tuples are immutable. Use a tuple when the collection should not change after creation, e.g. dictionary keys or function return values that bundle multiple results.</p>"]
                UNION ALL SELECT 1003, "How do I merge two dictionaries in Python 3.9+?",
                    "<p>I have two dicts and want a single dict containing keys from both, with values from the second overriding the first.</p>",
                    ["<p>Use the merge operator <code>|</code>:</p><pre><code>merged = a | b</code></pre><p>For older Python versions, copy <code>a</code> and call <code>update</code> with <code>b</code>.</p>"]
                UNION ALL SELECT 1004, "How does a list comprehension work?",
                    "<p>I keep seeing one-liners like <code>[x*2 for x in nums]</code>. How does this compare to a regular for loop?</p>",
                    ["<p>List comprehensions build a new list by evaluating an expression for each item in an iterable. They are equivalent to:</p><pre><code>result = []\\nfor x in nums:\\n    result.append(x*2)</code></pre><p>but more concise and slightly faster because the loop runs in C.</p>"]
                UNION ALL SELECT 1005, "What is the purpose of __init__.py?",
                    "<p>Some packages have an empty <code>__init__.py</code>, others have code inside. What is it for?</p>",
                    ["<p>It marks a directory as a regular Python package. Code inside runs when the package is first imported and is a good place for re-exports.</p><p>Since 3.3, namespace packages can omit it, but most projects keep one for explicitness.</p>"]
                UNION ALL SELECT 1006, "How do I read a JSON file in Python?",
                    "<p>What is the standard library way to load a JSON file from disk into a dict?</p>",
                    ["<p>Use <code>json.load</code> with a file handle:</p><pre><code>import json\\nwith open(\\"data.json\\") as f:\\n    data = json.load(f)</code></pre>"]
                UNION ALL SELECT 1007, "What is the difference between == and is?",
                    "<p>I sometimes see <code>x is None</code> and other times <code>x == None</code>. Which should I use?</p>",
                    ["<p><code>==</code> compares values via <code>__eq__</code>; <code>is</code> compares object identity. Use <code>is None</code> because <code>None</code> is a singleton — comparing identity is faster and unambiguous.</p>"]
                UNION ALL SELECT 1008, "How do I run an asyncio coroutine from sync code?",
                    "<p>I have an <code>async def</code> function and want to call it from a regular script entry point.</p>",
                    ["<p>Use <code>asyncio.run</code>:</p><pre><code>import asyncio\\nasyncio.run(my_coro())</code></pre><p>It creates a fresh event loop, runs the coroutine, and closes the loop on exit.</p>"]
                UNION ALL SELECT 1009, "How do I create a dataclass?",
                    "<p>I want a simple immutable record type with auto-generated <code>__init__</code> and <code>__repr__</code>.</p>",
                    ["<p>Decorate a class with <code>@dataclass(frozen=True)</code>:</p><pre><code>from dataclasses import dataclass\\n\\n@dataclass(frozen=True)\\nclass Point:\\n    x: float\\n    y: float</code></pre>"]
                UNION ALL SELECT 1010, "What is a generator and when should I use one?",
                    "<p>I keep seeing <code>yield</code> in functions instead of <code>return</code>. What does it do?</p>",
                    ["<p>A generator produces values lazily — each <code>yield</code> pauses the function until the next value is requested. Use generators for streaming large or infinite sequences without loading everything into memory.</p>"]
                UNION ALL SELECT 1011, "How do I iterate a dict in insertion order?",
                    "<p>Are dicts ordered in modern Python?</p>",
                    ["<p>Yes — since CPython 3.7, dicts preserve insertion order as a language guarantee. Just iterate with <code>for key, value in d.items()</code>.</p>"]
                UNION ALL SELECT 1012, "How do I catch multiple exception types in one except clause?",
                    "<p>I want a single block to handle both <code>ValueError</code> and <code>TypeError</code>.</p>",
                    ["<p>Pass a tuple to <code>except</code>:</p><pre><code>try:\\n    parse(value)\\nexcept (ValueError, TypeError) as exc:\\n    log.warning(\\"bad input: %s\\", exc)</code></pre>"]
            ),
            dated_questions AS (
                SELECT
                    TIMESTAMP("{end_date}") AS creation_date,
                    TIMESTAMP("{end_date}") AS last_edit_date,
                    question_id,
                    question_title,
                    question_body AS question_text,
                    answers
                FROM questions
            )
            SELECT * FROM dated_questions
            WHERE TRUE
                {f'AND TIMESTAMP_TRUNC(creation_date, DAY) BETWEEN TIMESTAMP("{start_date}") AND TIMESTAMP("{end_date}")' if is_incremental else ""}
            {limit_clause}
        """
        logging.info("Fetching synthetic Q&A data from BigQuery...")
        return bpd.read_gbq(query)

    def convert_html_to_markdown(html: str) -> str:
        """Convert HTML into Markdown for easier parsing and rendering after LLM response."""
        return markdownify(html).strip()

    def create_answers_markdown(answers: list) -> str:
        """Convert each answer's HTML to markdown and concatenate into a single markdown text."""
        answers_md = ""
        for index, answer_html in enumerate(answers):
            answers_md += (
                f"\n\n## Answer {index + 1}:\n"  # Answer number is H2 heading size
            )
            answers_md += convert_html_to_markdown(answer_html)
        return answers_md

    def create_table_if_not_exist(
        df: bpd.DataFrame,
        project_id: str,
        dataset_id: str,
        table_id: str,
        partition_column: str,
        location: str = location,
    ) -> None:
        """Create BigQuery table with time partitioning if it doesn't exist."""
        table_schema = bq_client.get_table(df.head(0).to_gbq()).schema
        table = bigquery.Table(
            f"{project_id}.{dataset_id}.{table_id}", schema=table_schema
        )
        table.time_partitioning = bigquery.TimePartitioning(
            type_=bigquery.TimePartitioningType.DAY, field=partition_column
        )

        dataset = bigquery.Dataset(f"{project_id}.{dataset_id}")
        dataset.location = location
        bq_client.create_dataset(dataset, exists_ok=True)
        bq_client.create_table(table=table, exists_ok=True)

    # Fetch and preprocess data
    logging.info("Fetching and preprocessing data...")
    df = fetch_sample_data(
        start_date=START_DATE.strftime("%Y-%m-%d"),
        end_date=END_DATE.strftime("%Y-%m-%d"),
    )
    df = (
        df.sort_values("last_edit_date", ascending=False)
        .drop_duplicates("question_id")
        .reset_index(drop=True)
    )
    logging.info("Data fetched and preprocessed.")

    # Convert content to markdown
    logging.info("Converting content to markdown...")

    # Create markdown fields efficiently
    df["question_title_md"] = (
        "# " + df["question_title"] + "\n"
    )  # Title is H1 heading size
    df["question_text_md"] = (
        df["question_text"].to_pandas().swifter.apply(convert_html_to_markdown) + "\n"
    )
    df["answers_md"] = df["answers"].to_pandas().swifter.apply(create_answers_markdown)

    # Create a column containing the whole markdown text
    df["full_text_md"] = (
        df["question_title_md"] + df["question_text_md"] + df["answers_md"]
    )
    logging.info("Content converted to markdown.")

    # Keep only necessary columns
    df = df[["last_edit_date", "question_id", "question_text", "full_text_md"]]

    # Split text into chunks
    logging.info("Splitting text into chunks...")
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        length_function=len,
    )

    df["text_chunk"] = (
        df["full_text_md"]
        .to_pandas()
        .astype(object)
        .swifter.apply(text_splitter.split_text)
    )
    logging.info("Text split into chunks.")

    # Create chunk IDs and explode chunks into rows.
    # Include a run timestamp in chunk_id to ensure uniqueness across runs.
    # This allows create-before-delete ingestion: new chunks never collide
    # with old ones, so we can safely create first, then delete stale data.
    logging.info("Creating chunk IDs and exploding chunks into rows...")
    run_ts = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    chunk_ids = [
        str(idx) for text_chunk in df["text_chunk"] for idx in range(len(text_chunk))
    ]
    df = df.explode("text_chunk").reset_index(drop=True)
    df["chunk_id"] = (
        df["question_id"].astype("string") + "__" + run_ts + "__" + chunk_ids
    )
    logging.info("Chunk IDs created and chunks exploded.")

    # No embedding generation needed — Vector Search 2.0 auto-generates embeddings
    df = df.assign(creation_timestamp=datetime.now(timezone.utc))

    # Store results in BigQuery
    PARTITION_DATE_COLUMN = "creation_timestamp"

    # Create and populate incremental table
    logging.info("Creating and populating incremental table...")
    create_table_if_not_exist(
        df=df,
        project_id=project_id,
        dataset_id=destination_dataset,
        table_id=destination_table,
        partition_column=PARTITION_DATE_COLUMN,
    )

    if_exists_mode = "append" if is_incremental else "replace"
    df.to_gbq(
        destination_table=f"{destination_dataset}.{destination_table}",
        if_exists=if_exists_mode,
    )
    logging.info("Incremental table created and populated.")

    # Create deduplicated table
    logging.info("Creating deduplicated table...")
    df_questions = bpd.read_gbq(
        f"{destination_dataset}.{destination_table}", use_cache=False
    )
    max_date_df = (
        df_questions.groupby("question_id")["creation_timestamp"].max().reset_index()
    )
    df_questions_dedup = max_date_df.merge(
        df_questions, how="inner", on=["question_id", "creation_timestamp"]
    )

    create_table_if_not_exist(
        df=df_questions_dedup,
        project_id=project_id,
        dataset_id=destination_dataset,
        table_id=deduped_table,
        partition_column=PARTITION_DATE_COLUMN,
    )

    df_questions_dedup.to_gbq(
        destination_table=f"{destination_dataset}.{deduped_table}",
        if_exists="replace",
    )
    logging.info("Deduplicated table created and populated.")
    # Set artifact metadata (important!)
    output_table.uri = (
        f"bq://{project_id}.{destination_dataset}.{deduped_table}"  # Full BQ URI
    )
    output_table.metadata["projectId"] = project_id
    output_table.metadata["datasetId"] = destination_dataset
    output_table.metadata["tableId"] = deduped_table
